---
- name: Play to demonstrate ansible tags
# Ansible has special tags
# a)always
# b)never
# c)all
# You can invoke multiples tags with --tags tag1,tag2.... 
# You can skip tags with --skip-tags tag1,tag2 ....
# You can invoke all the tags with --tags all ; this is default behavious
#
  hosts: localhost
  gather_facts: false
  tasks:
   - name: Task1 to print text
     debug:
      msg: "Task1 - Red planet"
     tags:
      - mars
      - never

   - name: Task2 to print text
     debug:
      msg: "Task2 - Venus planet"
     tags:
      - mist
      - always #always tag causes the task to always be executed even if not you did not specify in --tags option is used
   - name: Task3 to print text
     debug:
      msg: "Task3 - Jupiter planet"
     tags: mosaic 
   - name: Task4 to print text
     debug:
      msg: "Task4 - Earth planet"
     tags: 
      - blue
      - green
...
