---
- name: Play to change PermitRootLogin no to all the managed nodes
  hosts: all
  become: true
  vars:
   fname: /etc/ssh/sshd_config
  tasks:
   - name: Taks to replace the line
     lineinfile:
      path: "{{fname}}"
      regexp: '^PermitRootLogin yes'
      line: 'PermitRootLogin no'
      backup: yes
     notify:
      - Restart_SSH
      - Restart_SSH_Debian
     ignore_unreachable: yes
  handlers:
  - name: Restart_SSH
    service: 
     name: sshd
     state: restarted
    when: ansible_distribution|lower in ['redhat', 'centos']
  - name: Restart_SSH_Debian
    service:
     name: ssh
     state: restarted
    when: ansible_distribution|lower in ['debian']
...