---
- name: Ansible to install package if memory > 2048MB
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
  - name: Task to updtae the kernel if installed RAM is greater than 2GB
    yum:
     name: kernel
     state: latest
    when: ansible_memory_mb.real.total > 2048
  - name: Task to updtae the kernel if installed RAM is greater than 2GB
    debug:
     msg: "{{ansible_memory_mb}}"
...