---
- name: Demonstrate iterative statement in ansible
  hosts: localhost
  become: true
  gather_facts: false
  remote_user: ansible
  tasks:
   - name: Repeat this task for 5 times
     debug:
      msg: Hi I am Ansible, Call me {{item}}
     loop:
      - Blue
      - Green
      - Pink
      - Red
      - Yellow
...
#End