---
#Commonly used magic variables:
#-----------------------------
#hostvars: You can access variables defined by any host in the play
#--------
#groups: Print the dictionary or map with all groups in inventory and each group has the list of hosts that belongs to it.
#------
#group_names: List groups the current host is part of
#-----------
#inventory_hostname: Inventory name of current host being iterated over in the play
#------------------
- name: Play to demonstrate magic variables
  hosts: [192.168.10.200]
  become: true
  tasks:
  #- name: groups
  #  debug:
  #   var: groups
  #- name: inventory_hostname
  #  debug:
  #   var: inventory_hostname
  #- name: group_names
  #  debug:
  #   var: group_names
   - name: hostvars
     debug:
      var: hostvars
...
 
