#Ansible playbook can have multiple plays. This playbook demonstrates multiple
#plays in single playbook
---
- name: Play1 - Install samba
  hosts: [192.168.20.200,192.168.21.200]
  remote_user: ansible
  become: true
  tasks:
   - name: Task to install samba server package
     yum:
      name: samba
      state: latest
#End of the fist play
#Beginning of the secon Play
- name: Play2 - Start Samaba services
  hosts: [192.168.20.200,192.168.21.200]
  remote_user: ansible
  become: true
  tasks:
   - name: Task1 - Start Smbd
     service:
      name: smb
      state: started
   - name: Task2 - Start nmbd
     service:
      name: nmb
      state: started
#End of the second play
... 
#End of the playbook
