---
- name: play to replace PermitRootLogin in /etc/ssh/sshd_config file
  hosts: 192.168.24.200
  gather_facts: no
  become: true
  remote_user: ansible
  tasks:
   - name: Replace PermitRootLogin 
     lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^PermitRootLogin
      line: "PermitRootLogin no"
      backup: yes
   - name: Restart sshd 
     service:
      name: sshd
      state: restarted
...
#End of the play