---
#Configure cron job
##0   8,18,20   1-5  1,3,4,6   2            /usr/sbin/vgs>/tmp/vgs.out
#Mins Hours    Date  Month     Dayoftheweek /path/to/command
#
- name: Demonstrate cron module to schedule a job
  hosts: 192.168.35.200
  become: yes
  tasks:
   - name: configure cron job
     cron:
      name: "My Cron"
      minute: "0" #Minutes ranges from 0 to 59.
      hour: "8,18,20" #8am, 6pm, 8pm; hours ranges from 0 - 23.
      #ignoring day of the week and week assumed as *
      weekday: "2" #Tuesday
      day: "1-5" #day of the month the job should run; in this example date is rage from 1 to 5.
      month: "1,3,4,6" #Month of the year ; in this example jan, march, april and june.
      job: "/usr/sbin/vgs > /tmp/vgs.out" #this is path to program or script to run.
      #disabled: true #Tab is commented out if disabled.
      state: absent
...
#End