---
- name: Demonstrate uri module
  hosts: localhost
  become: true
  remote_user: ansible
  gather_facts: false
  tasks:
  - name: Task to demonstrate uri module
    uri:
     url: http://192.168.35.200/index.html
     return_content: yes
    register: out
    ignore_errors: true
  - name: Check if the page is working
    debug:
     msg: The page is working
    when: out.status == 200
  - name: Check if the page is not working
    debug:
     msg: The page is not found
    when: out.status == 404
... 