---
- name: create a file with some content. use copy module for the same
  hosts: localhost #create the file in the server where you are running this play ie localhost
  become: true
  remote_user: ansible
  tasks:
   - name: create a file with some content
     copy:
      dest: /etc/.sec.conf #create a file
      content: "username: ansible \npassword: ansible" #put some content
      mode: '0400' #file permissions
      owner: root  #file owner
      group: root  #file group owner
...
#end of the play