---
- name: Demonstrate shell module 
  hosts: localhost
  become: true
  gather_facts: false
  remote_user: ansible
  tasks:
   - name: Task to execute shell commmand
     shell: /usr/sbin/vgs
     register: v_out
   - name: Print v_out 
     debug:
      #var: v_out
      msg: "{{v_out.stdout_lines}}"
...