---
- name: Demonstrate ansible if condition. when condition
  hosts: localhost
  gather_facts: false
  become: true
  vars:
  # res1: false
    res1: true
  remote_user: ansible
  tasks:
   - name: Task to test the condition
     debug:
      msg: I am always true
     when: res1
...